#!/bin/sh

cd /home/ankit/wallpapers/

path=/home/ankit/wallpapers/$(ls . | shuf -n 1)

wal -i $path

cd /home/ankit/dwm/
cat ~/.root.txt | sudo -S make clean install
cd /home/ankit/st/
cat ~/.root.txt | sudo -S make clean install
cd /home/ankit/dmenu
cat ~/.root.txt | sudo -S make clean install


